### ISSUE TITLE
Offensive Language On Disability Status

### ISSUE THREAD

**Issue by cerberlink** [Devographics/Monorepo#200]
I took a screenshot of what I have seen it. 

The terms, `speech impairment` and `hearing impairments`, are unacceptable. I wonder if you can put a wordsmith on those terms with appropriate terms. ```Deaf and Hard of Hearing``` are acceptable. Please refer to this [style guide](https://ncdj.org/style-guide/). 

Thanks!

![Screenshot 2023-01-17 at 4 30 10 PM](https://user-images.githubusercontent.com/11153290/213050117-2bd52813-650f-4bd1-a8dc-0ec109ff52cd.png)
![Screenshot 2023-01-17 at 4 30 27 PM](https://user-images.githubusercontent.com/11153290/213050174-292e55ce-9a32-44aa-afca-e774f14a10ea.png)

**Comment by SachaG** [comment]
Thanks for the input! I haven't received other negative feedback about those terms so far so for now I will assume the majority of respondents (including those experiencing these conditions) are OK with them, but I am definitely open to changing the wording if it turns out I'm wrong and that the current terms are indeed an issue.
