### ISSUE TITLE
add canonical urls to all pages

### ISSUE THREAD

**Issue by Kilian** [Devographics/Monorepo#25]
Adding this would be nice, but it's a little complex to get right especially with i18n.

**Comment by eric-burel** [comment]
What do you mean by canonical URL?

**Comment by Kilian** [comment]
Canonical URLs are a Link element that tell google and other crawlers what the one true location of a resource is (e.g. with multiple languages, or with the site being available at both the bare domain and the www. subdomain). More: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-link-method

This issue was more a reminder for myself when I did a round of responsive/a11y/quality updates in 2021.

**Comment by eric-burel** [comment]
Gonna close because we do not really have much content aside the home page, and for all page the page URL should be considered the canonical URL I think

I've however updated the sitemap so it includes home + surveys home

We could technically also include read-only survey outline but they are not content per se

The user specific page are not part of the sitemap
