### ISSUE TITLE
Reading list email is empty

### ISSUE THREAD

**Issue by sebastiansandqvist** [Devographics/Monorepo#310]
This is the complete content of the email I received when requesting the reading list by email:

```
Your State of HTML 2023 Reading List

You are receiving this email because you completed the State of HTML 2023 survey (https://survey.devographics.com/survey/state-of-html/2023) and asked to receive a copy of your reading list.
```

My reading list on that same page at the end of the survey has about a dozen items in it:
![IMG_2243](https://github.com/Devographics/Monorepo/assets/2024396/ef2eb473-1b56-42f4-83d9-853ba84e8ffb)

**Comment by SachaG** [comment]
Weird, I just tested it myself and it seemed to work. Maybe the issue is with one of the specific items you added? Would you be able to paste the entire contents of your reading list in here?

**Comment by CNFloss** [comment]
I am experiencing the same issue.

**Comment by SachaG** [comment]
@CNFloss could you let me know the items that were in your list?

**Comment by CNFloss** [comment]
@SachaG I actually can't now.  I tried to check out my results in a different browser and instead of going back in through my email login link, like a dummy I re-typed my email to get a new login link and it reset everything.  I can retake the survey and see if the same problem occurs and send you the results if you like.  I just wasn't sure about submitting more than once, I would assume it's not a huge deal but just in case I didn't.

**Comment by eric-burel** [comment]
Closing as inactive, feel free to comment if you want to reopen
