### ISSUE TITLE
Pain point text inputs unresponsive

### ISSUE THREAD

**Issue by LostKobrakai** [Devographics/Monorepo#315]
I have a hard time filling the pain point text inputs because it seems to regularly swallow keyboard input.

FF Developer Edition 118.0b9 on Mac OS

**Comment by eric-burel** [comment]
Can repro on FF 117 but not on Chrome, sorry about that
Will investigate

**Comment by eric-burel** [comment]
I've refactored it a bit to use fully uncontrolled inputs, and memoize relevant callbacks
It's tricky to handle because we need state to display the right number of inputs, but we don't want state for the input values as it causes too many rerenders and somehow firefox can't stand that (despite using a correct key)

New version seems better, it doesn't lose data anymore due to weird race conditions, is a bit shorter
It relies on a lot of annoying useCallback though but it seems to do the job

It can't be controlled so updating the textlist from another component would probably not work (while most other inputs are controlled, so you can change their value from another value) but I think that's an ok tradeoff for now
