### ISSUE TITLE
Locale redirect doesn't respect locale set in URL

### ISSUE THREAD

**Issue by SachaG** [Devographics/Monorepo#403]
Reproduction:

- Go to https://survey.devographics.com/
- Be redirected to https://survey.devographics.com/en-US
- Switch to Russian
- Be redirected to https://survey.devographics.com/ru-RU
- Go to https://survey.devographics.com/en-US
- **!** Be redirected to https://survey.devographics.com/ru-RU

**Comment by eric-burel** [comment]
This was the expected behaviour from code indeed
![image](https://github.com/user-attachments/assets/0d81abbf-24b3-4f88-a325-3afebf998c22)

So changing to priorize first the locale from the URL, then cookies, then accept language

When sharing the survey with "en-US" it means that language won't switch automatically but that's not a big deal

**Comment by eric-burel** [comment]
Yep I've just pushed the change so we favour explicit URL param, then cookie, then accept-language header, then default
I've taken the occasion to  slightly improve the LocaleSwitcher it should be more robust (however I assume the "lang" param is always defined).
