### ISSUE TITLE
Interested button doesn't create reading list

### ISSUE THREAD

**Issue by joeldcanfield** [Devographics/Monorepo#421]
clicked 'Interested' button on quite a few items, but can't find where a list of such appears. 

completion page says I didn't add anything to my reading list. assumed that's what the 'Interested' button was doing.

**Comment by SachaG** [comment]
There's actually a distinct "+" button to add things to your reading list. 

I can see the reason for the confusion though, and maybe it'd be better if the "interested" button did actually auto-add things to the reading list. 

The only downsides are 1) it might add too many things and 2) some items don't have the interested/not interested options but you might still want to add them to the reading list.

**Comment by joeldcanfield** [comment]
What is the purpose of the Interested button and where is that explained?

**Comment by SachaG** [comment]
It's just a datapoint we collect. See https://2023.stateofjs.com/en-US/libraries/ for an example of a chart that uses it.

**Comment by joeldcanfield** [comment]
Had the two been proximal I would have wondered why there were two buttons doing the same thing, and then realized or asked.

Preposterous ask: can the "add to reading list" icon appear next to any item with which the user interacts?

**Comment by SachaG** [comment]
Actually, the current workaround is that the first time you click "interested" it should show you a tooltip telling you about the reading list feature. But maybe that tooltip didn't trigger for whatever reason. 

How about this: maybe at the end of the survey you could have your reading list, and then below that the option to also add all the features you were interested about but *didn't* add?

**Comment by joeldcanfield** [comment]
Bingo: what confused me was that the first time I clicked "Interested" it mentioned the reading list, and I conflated the two. That's where the distinction didn't happen for me. Perhaps clarification within the interested-button popup ("want to learn more? use the + button to add it to your reading list")

I don't see value in adding anything at the end. As a new user, I need to know clearly up front what the two features do and what they don't. Otherwise I'm turning your data point ("user is interested in implementing this feature" which is my guess at what the button is for; I'm still not clear) into my data point ("what does this do?" which is a far cry from "I need this in my life.")

**Comment by echocrow** [comment]
> Bingo: what confused me was that the first time I clicked "Interested" it mentioned the reading list, and I conflated the two. 

continuing to echo what @joeldcanfield mentioned: it was the same for me. first time I clicked "Interested", the tooltip popped up unexpectedly. but wanting to move on, i briefly scanned the words, picked up "reading list", dismissed and carried on, now thinking "Interested" added to the list.

this is partially self inflicting by me auto-dismissing modals/tooltips before thoroughly reading them. at the same time, I find unprompted tutorials are typically trying to treat a symptom instead of the underlying cause.

perhaps the UI/UX could better convey this somehow? or, although also bit of a duct tape solution, perhaps a non-interactive sample question at the very start, highlighting features like the [+] reading list button, or the "skip" option? something that is static (not dependent on a user interaction, and cannot be dismissed), thus also something a user can return to later to read again, or scroll past if familiar.

> Otherwise I'm turning your data point ("user is interested in implementing this feature" [...]) into my data point [...]

also guilty. there's now a few "Interested" checks on things I don't _think_ I'll be using any time soon, but wanted to read up on just in case.

**Comment by eric-burel** [comment]
Could we use a "bookmark" icon ? Which is more usual eg on Twitter you'd never conflate the "like" button for the bookmark button? Might just be a tiny UX issue

**Comment by eric-burel** [comment]
Closing as won't fix unless we have a PR, I think the reading list should not become too big or should rather be part of the results app more than the survey app
